language: java
sudo: false
dist: xenial

jdk:
  - openjdk8

services:
  - docker

before_install: pyenv global 3.7
install:
  - pip install --user --upgrade git+https://github.com/neo4j-drivers/boltkit.git@4.0-updates-for-java#egg=boltkit

script:
  - mvn clean verify -DbuildParameters="--user $UID"
